name: Hello world

on:
  workflow_dispatch:

jobs:
  multishell:
    runs-on: ubuntu-latest
    steps:
      - name: Multishell-step
        run: |
          echo "This is line one"
          echo "This is line two"
